# Generated by Django 5.2.17 on 2026-09-07 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0009_event_sales_window"),
        ("ordering", "0002_order_line_inventory_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("VALID", "VALID"), ("USED", "USED"), ("VOID", "VOID")],
                        default="VALID",
                        max_length=16,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="catalog.event",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="ordering.orderline",
                    ),
                ),
                (
                    "ticket_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="catalog.ticketcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ticketing_ticket",
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="ix_ticket_user_created"),
                    models.Index(fields=["event", "status"], name="ix_ticket_event_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order_line", "sequence"), name="uq_ticket_line_sequence"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gt", 0)), name="ck_ticket_sequence_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["VALID", "USED", "VOID"])),
                        name="ck_ticket_status_valid",
                    ),
                ],
            },
        ),
    ]
