# Generated by Django 5.2.17 on 2026-09-08 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_version",
            field=models.PositiveIntegerField(
                default=1, help_text="Incrémente à chaque transfert pour invalider les QR déjà ouverts."
            ),
        ),
        migrations.CreateModel(
            name="TicketTransferAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_audits",
                        to="ticketing.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticketing_ticket_transfer_audit",
                "indexes": [
                    models.Index(fields=["ticket", "created_at"], name="ix_ticket_transfer_ticket_time")
                ],
            },
        ),
    ]
