# Generated by Django 5.1.3 on 2026-08-12 15:19

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_infrastructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="sequence",
            field=models.BigIntegerField(
                db_default=django.db.models.expressions.RawSQL(
                    "nextval('outbox_event_sequence_seq')",
                    params=[],
                ),
                editable=False,
                unique=True,
            ),
        ),
    ]