# Generated by Django 5.2.17 on 2026-08-17 18:54

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("org_name", models.CharField(max_length=120)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("SUSPENDED", "SUSPENDED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=5),
                ),
                ("vat_number", models.CharField(blank=True, max_length=32, null=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizers_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizing_organizer",
                "indexes": [models.Index(fields=["validation_status"], name="ix_organizer_status")],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("org_name"), name="uq_organizer_org_name_ci"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("commission_rate__gte", 0), ("commission_rate__lte", 1)),
                        name="ck_organizer_commission_rate_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("validation_status__in", ["PENDING", "APPROVED", "REJECTED", "SUSPENDED"])
                        ),
                        name="ck_organizer_status_valid",
                    ),
                ],
            },
        ),
    ]
