# Generated by Django 5.2.17 on 2026-08-26 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scanner",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "INVITED"),
                            ("EMAIL_SENT", "EMAIL_SENT"),
                            ("OPENED", "OPENED"),
                            ("ACTIVE", "ACTIVE"),
                            ("LEAVE_REQUESTED", "LEAVE_REQUESTED"),
                            ("INVITATION_CANCELLED", "INVITATION_CANCELLED"),
                            ("DELETED", "DELETED"),
                        ],
                        default="INVITED",
                        max_length=32,
                    ),
                ),
                ("scanner_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("organizer_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("opened_scanner_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_organizer_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("active_scanner_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("active_organizer_email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scanner_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scanners",
                        to="organizing.organizer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scanner_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizing_scanner",
                "indexes": [models.Index(fields=["organizer", "status"], name="ix_scanner_org_status")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "INVITED",
                                    "EMAIL_SENT",
                                    "OPENED",
                                    "ACTIVE",
                                    "LEAVE_REQUESTED",
                                    "INVITATION_CANCELLED",
                                    "DELETED",
                                ],
                            )
                        ),
                        name="ck_scanner_status_valid",
                    )
                ],
            },
        ),
    ]
