# Generated by Django 5.2.17 on 2026-08-29 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0003_scanner_invited_email_scanner_invited_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannerCredentialRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("FULFILLED", "FULFILLED")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scanner_credential_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_requests",
                        to="organizing.scanner",
                    ),
                ),
            ],
            options={
                "db_table": "organizing_scanner_credential_request",
                "indexes": [
                    models.Index(fields=["scanner", "status", "-created_at"], name="ix_scan_cred_req_status")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("scanner",),
                        name="uq_scanner_pending_credential_request",
                    )
                ],
            },
        ),
    ]
