# Generated by Django 5.2.17 on 2026-08-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0004_scannercredentialrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="scannercredentialrequest",
            name="reissue_organizer_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scannercredentialrequest",
            name="reissue_scanner_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scannercredentialrequest",
            name="request_organizer_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scannercredentialrequest",
            name="request_scanner_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
