# Generated by Django 5.2.17 on 2026-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0006_scanner_archived_at_scanner_archived_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanner",
            name="leave_rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="leave_rejected_organizer_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="leave_rejected_scanner_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="leave_request_organizer_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="leave_request_scanner_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="leave_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
