# Generated by Django 5.2.17 on 2026-08-30 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0007_scanner_leave_rejected_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannerRevocationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("REVOKE", "REVOKE"), ("LEAVE_ACCEPT", "LEAVE_ACCEPT")], max_length=20
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanner_revocation_challenges",
                        to="organizing.organizer",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanner_revocation_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocation_challenges",
                        to="organizing.scanner",
                    ),
                ),
            ],
            options={
                "db_table": "organizing_scanner_revocation_challenge",
                "indexes": [
                    models.Index(
                        fields=["organizer", "scanner", "action", "consumed_at"],
                        name="ix_scanner_revoke_otp_open",
                    ),
                    models.Index(fields=["expires_at"], name="ix_scanner_revoke_otp_exp"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("attempts__lte", models.F("max_attempts"))),
                        name="ck_scanner_revoke_otp_attempts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code_hash__regex", "^[0-9a-f]{64}$")),
                        name="ck_scanner_revoke_otp_hash",
                    ),
                ],
            },
        ),
    ]
