# Generated by Django 5.2.17 on 2026-08-30 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0008_scannerrevocationchallenge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerReactivationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organizer_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("APPROVED", "APPROVED"), ("REJECTED", "REJECTED")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("request_organizer_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("request_admin_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("decision_organizer_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("decision_admin_email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reactivation_requests",
                        to="organizing.organizer",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizer_reactivation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizer_reactivation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizing_organizer_reactivation_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organizer", "-created_at"], name="ix_org_react_org_created"),
                    models.Index(fields=["status", "-created_at"], name="ix_org_react_status_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("organizer",),
                        name="uq_org_pending_reactivation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["PENDING", "APPROVED", "REJECTED"])),
                        name="ck_org_reactivation_status",
                    ),
                ],
            },
        ),
    ]
