# Generated by Django 5.2.17 on 2026-09-03 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizing", "0010_scanner_leave_request_otp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerCommissionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "proposer_role",
                    models.CharField(choices=[("ORGANIZER", "ORGANIZER"), ("ADMIN", "ADMIN")], max_length=16),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizer_commission_proposals_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_proposals",
                        to="organizing.organizer",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizer_commission_proposals_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizing_organizer_commission_proposal",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(fields=["organizer", "sequence"], name="ix_org_commission_prop_seq")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organizer", "sequence"), name="uq_org_commission_proposal_seq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gte", 0), ("rate__lte", 1)),
                        name="ck_org_commission_proposal_rate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("proposer_role__in", ["ORGANIZER", "ADMIN"])),
                        name="ck_org_commission_proposer_role",
                    ),
                ],
            },
        ),
    ]
