# Generated by Django 5.2.17 on 2026-08-18 17:45

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "catalog_category",
                "indexes": [models.Index(fields=["name"], name="ix_category_name")],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"), name="uq_category_name_ci"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "DRAFT"), ("PUBLISHED", "PUBLISHED"), ("ARCHIVED", "ARCHIVED")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_event",
                "indexes": [
                    models.Index(fields=["status"], name="ix_event_status"),
                    models.Index(fields=["starts_at"], name="ix_event_starts_at"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"), name="uq_event_name_ci"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="ck_event_dates_coherent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "ARCHIVED"])),
                        name="ck_event_status_valid",
                    ),
                ],
            },
        ),
    ]
