# Generated by Django 5.2.17 on 2026-08-25 19:38

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_event_organizer"),
        ("organizing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("quota", models.PositiveIntegerField()),
                ("sold_count", models.PositiveIntegerField(default=0)),
                ("unit_price_cents", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "catalog_ticket_category",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="capacity_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="image_key",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="event",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_total__isnull", True), ("capacity_total__gt", 0), _connector="OR"
                ),
                name="ck_event_capacity_positive",
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_categories",
                to="catalog.event",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcategory",
            index=models.Index(fields=["event"], name="ix_ticket_category_event"),
        ),
        migrations.AddConstraint(
            model_name="ticketcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("event"),
                name="uq_ticket_category_event_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("quota__gt", 0)), name="ck_ticket_category_quota_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("sold_count__lte", models.F("quota"))),
                name="ck_ticket_category_sold_lte_quota",
            ),
        ),
    ]
