# Generated by Django 5.2.17 on 2026-08-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_ticketcategory_event_capacity_total_event_image_key_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticketcategory",
            name="ix_ticket_category_event",
        ),
    ]
