# Generated by Django 5.2.17 on 2026-08-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_ticketcategory_ix_ticket_category_event"),
        ("organizing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="ck_event_status_valid",
        ),
        migrations.AddField(
            model_name="event",
            name="lifecycle_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="lifecycle_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("POSTPONED", "POSTPONED"),
                    ("SUSPENDED", "SUSPENDED"),
                    ("CANCELLED", "CANCELLED"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "PUBLISHED", "POSTPONED", "SUSPENDED", "CANCELLED", "ARCHIVED"])
                ),
                name="ck_event_status_valid",
            ),
        ),
    ]
