# Generated by Django 5.2.17 on 2026-08-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_event_lifecycle"),
        ("organizing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_categories",
                to="organizing.organizer",
            ),
        ),
    ]
