# Generated by Django 5.2.17 on 2026-08-30 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_organizer_event_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventScannerAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scanner_id", models.UUIDField()),
                ("assigned_by_id", models.UUIDField()),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                ("unassigned_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanner_assignments",
                        to="catalog.event",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_event_scanner_assignment",
                "indexes": [
                    models.Index(fields=["event", "unassigned_at"], name="ix_ev_scan_event_active"),
                    models.Index(fields=["scanner_id", "unassigned_at"], name="ix_ev_scan_scanner_active"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("unassigned_at__isnull", True)),
                        fields=("event", "scanner_id"),
                        name="uq_event_scanner_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("unassigned_at__isnull", True), ("unassigned_by_id__isnull", True)),
                            models.Q(("unassigned_at__isnull", False), ("unassigned_by_id__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_ev_scan_unassign_trace",
                    ),
                ],
            },
        ),
    ]
