# Generated by Django 5.2.17 on 2026-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_event_sales_window"),
        ("organizing", "0012_organizer_commission_agreed_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="ck_event_status_valid",
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("POSTPONED", "POSTPONED"),
                    ("SUSPENDED", "SUSPENDED"),
                    ("CANCELLED", "CANCELLED"),
                    ("COMPLETED", "COMPLETED"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "DRAFT",
                            "PUBLISHED",
                            "POSTPONED",
                            "SUSPENDED",
                            "CANCELLED",
                            "COMPLETED",
                            "ARCHIVED",
                        ],
                    )
                ),
                name="ck_event_status_valid",
            ),
        ),
    ]
