# Generated by Django 5.2.17 on 2026-09-05 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordering", "0002_order_line_inventory_relations"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=40)),
                ("provider_intent_id", models.CharField(max_length=200, unique=True)),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("CREATED", "CREATED"), ("SUCCEEDED", "SUCCEEDED"), ("FAILED", "FAILED")],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("client_secret", models.CharField(max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="ordering.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_intent",
                "indexes": [
                    models.Index(fields=["order", "created_at"], name="ix_pay_int_order_created"),
                    models.Index(fields=["status"], name="ix_pay_int_status"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gt", 0)), name="ck_payment_intent_amount_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["CREATED", "SUCCEEDED", "FAILED"])),
                        name="ck_payment_intent_status_valid",
                    ),
                ],
            },
        ),
    ]
