# Generated by Django 5.2.17 on 2026-09-08 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_event_sales_window"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_cents", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("SUCCEEDED", "SUCCEEDED"), ("FAILED", "FAILED")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("provider_refund_id", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("failure_reason", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_refunds",
                        to="catalog.event",
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_refund",
                "indexes": [
                    models.Index(fields=["event", "status"], name="ix_pay_ref_event_status"),
                    models.Index(fields=["status", "created_at"], name="ix_pay_ref_status_created"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gt", 0)), name="ck_payment_refund_amount_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["PENDING", "SUCCEEDED", "FAILED"])),
                        name="ck_payment_refund_status_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("payment_intent", "event"), name="uq_payment_refund_intent_event"
                    ),
                ],
            },
        ),
    ]
