# Generated by Django 5.2.17 on 2026-08-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
