# Generated by Django 5.2.17 on 2026-08-13 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, default="", max_length=60)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "android"), ("ios", "ios"), ("web", "web")], max_length=10
                    ),
                ),
                ("bound_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USER_RESET", "USER_RESET"),
                            ("ADMIN", "ADMIN"),
                            ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                            ("STALE", "STALE"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_device",
            },
        ),
        migrations.CreateModel(
            name="MfaChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("DEVICE_RESET", "DEVICE_RESET"),
                            ("STEP_UP", "STEP_UP"),
                            ("EMAIL_CHANGE", "EMAIL_CHANGE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_mfa_challenge",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("family_id", models.UUIDField()),
                ("refresh_jti", models.UUIDField(unique=True)),
                ("auth_level", models.PositiveSmallIntegerField(default=1)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOGOUT", "LOGOUT"),
                            ("ROTATION_REUSE", "ROTATION_REUSE"),
                            ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                            ("ADMIN", "ADMIN"),
                            ("DEVICE_RESET", "DEVICE_RESET"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nul pour ORGANIZER et ADMIN, exemptés du verrou d'appareil (ADR-03).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="identity.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_session",
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["user", "-bound_at"], name="ix_device_history"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("user",),
                name="uq_device_active_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("fingerprint__regex", "^[0-9a-f]{64}$")),
                name="ck_device_fingerprint_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("platform__in", ["android", "ios", "web"])),
                name="ck_device_platform_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_reason__isnull", True),
                    ("revoked_reason__in", ["USER_RESET", "ADMIN", "PASSWORD_CHANGE", "STALE"]),
                    _connector="OR",
                ),
                name="ck_device_revoked_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", True), ("revoked_reason__isnull", True)),
                    models.Q(("revoked_at__isnull", False), ("revoked_reason__isnull", False)),
                    _connector="OR",
                ),
                name="ck_device_revocation_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="mfachallenge",
            index=models.Index(fields=["user", "purpose", "consumed_at"], name="ix_mfa_open"),
        ),
        migrations.AddIndex(
            model_name="mfachallenge",
            index=models.Index(fields=["expires_at"], name="ix_mfa_purge"),
        ),
        migrations.AddConstraint(
            model_name="mfachallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", models.F("max_attempts"))),
                name="ck_mfa_attempts_within_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="mfachallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["DEVICE_RESET", "STEP_UP", "EMAIL_CHANGE"])),
                name="ck_mfa_purpose_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mfachallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("code_hash__regex", "^[0-9a-f]{64}$")),
                name="ck_mfa_code_hash_is_a_digest",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["family_id"], name="ix_session_family"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user", "revoked_at"], name="ix_session_user_active"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["expires_at"], name="ix_session_purge"),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("auth_level__in", [1, 2])), name="ck_session_auth_level_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                name="ck_session_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_reason__isnull", True),
                    (
                        "revoked_reason__in",
                        ["LOGOUT", "ROTATION_REUSE", "PASSWORD_CHANGE", "ADMIN", "DEVICE_RESET"],
                    ),
                    _connector="OR",
                ),
                name="ck_session_revoked_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", True), ("revoked_reason__isnull", True)),
                    models.Q(("revoked_at__isnull", False), ("revoked_reason__isnull", False)),
                    _connector="OR",
                ),
                name="ck_session_revocation_coherent",
            ),
        ),
    ]
