# Generated by Django 5.2.17 on 2026-08-13 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_device_mfachallenge_session_device_ix_device_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="issued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="session",
            name="last_used_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
