# Generated by Django 5.2.17 on 2026-08-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_alter_session_issued_at_alter_session_last_used_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mfachallenge",
            name="ck_mfa_purpose_valid",
        ),
        migrations.AlterField(
            model_name="mfachallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("DEVICE_RESET", "DEVICE_RESET"),
                    ("STEP_UP", "STEP_UP"),
                    ("EMAIL_CHANGE", "EMAIL_CHANGE"),
                    ("PASSWORD_RESET", "PASSWORD_RESET"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="mfachallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purpose__in", ["DEVICE_RESET", "STEP_UP", "EMAIL_CHANGE", "PASSWORD_RESET"])
                ),
                name="ck_mfa_purpose_valid",
            ),
        ),
    ]
