# Generated by Django 5.2.17 on 2026-08-26 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("identity", "0008_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="temporary_password_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role_id", uuid.UUID("91e56bcb-d23e-5169-a1f3-655e1e44f277")),
                    models.Q(("date_of_birth__isnull", False), ("terms_accepted_at__isnull", False)),
                    _connector="OR",
                ),
                name="ck_user_compliance_or_scanner",
            ),
        ),
    ]
