# Generated by Django 5.2.17 on 2026-08-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0009_user_must_change_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
