# Generated by Django 5.2.17 on 2026-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_alter_user_must_change_password"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="ck_session_revoked_reason_valid",
        ),
        migrations.AlterField(
            model_name="session",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOGOUT", "LOGOUT"),
                    ("ROTATION_REUSE", "ROTATION_REUSE"),
                    ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                    ("ADMIN", "ADMIN"),
                    ("DEVICE_RESET", "DEVICE_RESET"),
                    ("SCANNER_REMOVED", "SCANNER_REMOVED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_reason__isnull", True),
                    (
                        "revoked_reason__in",
                        [
                            "LOGOUT",
                            "ROTATION_REUSE",
                            "PASSWORD_CHANGE",
                            "ADMIN",
                            "DEVICE_RESET",
                            "SCANNER_REMOVED",
                        ],
                    ),
                    _connector="OR",
                ),
                name="ck_session_revoked_reason_valid",
            ),
        ),
    ]
