# Generated by Django 5.2.17 on 2026-08-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0011_remove_session_ck_session_revoked_reason_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temporary_password_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="temporary_password_generation",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
