# Generated by Django 5.2.17 on 2026-09-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0013_session_client_and_replaced_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOGOUT", "LOGOUT"),
                    ("ROTATION_REUSE", "ROTATION_REUSE"),
                    ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                    ("ADMIN", "ADMIN"),
                    ("DEVICE_RESET", "DEVICE_RESET"),
                    ("SCANNER_REMOVED", "SCANNER_REMOVED"),
                    ("REPLACED", "REPLACED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
