# Generated by Django 5.2.17 on 2026-09-07 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizing", "0012_organizer_commission_agreed_at"),
        ("ticketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketAdmission",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admitted_at", models.DateTimeField()),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_admissions",
                        to="organizing.scanner",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission",
                        to="ticketing.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "access_ticket_admission",
                "indexes": [
                    models.Index(fields=["scanner", "admitted_at"], name="ix_admission_scanner_time")
                ],
            },
        ),
    ]
