# Generated by Django 5.2.17 on 2026-09-07 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
        ("catalog", "0009_event_sales_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAdmissionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_admission_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_sessions",
                        to="catalog.event",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_admission_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "access_event_admission_session",
                "indexes": [models.Index(fields=["event", "closed_at"], name="ix_access_admit_evt_open")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("closed_at__isnull", True)),
                        fields=("event",),
                        name="uq_admission_session_event_open",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("closed_at__isnull", True), ("closed_by__isnull", True)),
                            models.Q(("closed_at__isnull", False), ("closed_by__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_admission_session_closure_trace",
                    ),
                ],
            },
        ),
    ]
