# Generated by Django 5.2.17 on 2026-09-07 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_eventadmissionsession"),
        ("organizing", "0012_organizer_commission_agreed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannerPresence",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField()),
                (
                    "scanner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_presence",
                        to="organizing.scanner",
                    ),
                ),
            ],
            options={
                "db_table": "access_scanner_presence",
            },
        ),
    ]
