# Generated by Django 5.2.17 on 2026-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0003_scannerpresence"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventadmissionsession",
            name="scheduled_starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de début de la programmation pour laquelle la session a été ouverte.",
                null=True,
            ),
        ),
    ]
