# Generated by Django 5.2.17 on 2026-09-08 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_eventadmissionsession_scheduled_starts_at"),
        ("catalog", "0009_event_sales_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventadmissionsession",
            name="ck_admission_session_closure_trace",
        ),
        migrations.AddField(
            model_name="eventadmissionsession",
            name="closed_automatically",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="eventadmissionsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_automatically", False),
                        ("closed_by__isnull", True),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("closed_automatically", False),
                        ("closed_by__isnull", False),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("closed_automatically", True),
                        ("closed_by__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_admission_session_closure_trace",
            ),
        ),
    ]
