# Generated by Django 5.2.17 on 2026-09-08 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0005_remove_eventadmissionsession_ck_admission_session_closure_trace_and_more"),
        ("catalog", "0010_remove_event_ck_event_status_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFinalReport",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField()),
                ("tickets_sold_count", models.PositiveIntegerField(default=0)),
                ("tickets_used_count", models.PositiveIntegerField(default=0)),
                ("tickets_voided_count", models.PositiveIntegerField(default=0)),
                ("tickets_absent_count", models.PositiveIntegerField(default=0)),
                ("gross_revenue_cents", models.PositiveIntegerField(default=0)),
                ("refunds_cents", models.PositiveIntegerField(default=0)),
                ("net_revenue_cents", models.PositiveIntegerField(default=0)),
                ("commission_rate", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("commission_cents", models.PositiveIntegerField(default=0)),
                ("organizer_net_cents", models.PositiveIntegerField(default=0)),
                ("scanner_stats", models.JSONField(default=list)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_report",
                        to="catalog.event",
                    ),
                ),
            ],
            options={
                "db_table": "access_event_final_report",
                "indexes": [models.Index(fields=["generated_at"], name="ix_final_report_generated")],
            },
        ),
    ]
